# Variables del Hospital de Algeciras

Con el objetivo de obtener índices útiles para la gestión hospitalaria basados en técnicas estadísticas multivariantes descriptivas se recogió información del Hospital de Algeciras correspondiente
a los ingresos hospitalarios del período 2007-2008. Se estudiaron las siguientes variables habitualmente monitorizadas por el Servicio Andaluz de Sald del Sistema Nacional de Salud Español:

NI: número de ingresos

MO: tasa de mortalidad

RE: tasa de egresos

NE: número de consultas externas

ICM: índice cardíaco máximo

ES: número de estancias

Las variables se midieron en un total de 22486 ingresos.

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

In [7]:
datos = pd.read_csv("hospitales-escalado.csv")   # dataFrame escalado a media cero, más fácil de usar que hospitales.csv
datosNP = datos.to_numpy()
print(datos)
print(datosNP)

                Servicio        NI     MO        RE        NE       ICM  \
0                Cirugia  0.358385  0.304  0.244275  0.257901  0.564103   
1        Tocoginecologia  1.000000  0.024  0.221374  0.065260  0.008547   
2            Hematologia  0.000000  0.328  0.503817  0.356053  1.000000   
3            Cardiologia  0.040369  0.176  0.282443  0.000000  0.675214   
4              Digestivo  0.044879  0.472  0.229008  0.294376  0.470085   
5       Medicina.Interna  0.790638  1.000  0.404580  0.781110  0.452991   
6             Neumologia  0.015675  0.408  0.320611  0.020049  0.820513   
7   Otorrinolaringologia  0.034572  0.168  0.160305  0.799670  0.307692   
8           Oftalmologia  0.107580  0.000  0.000000  0.788719  0.264957   
9              Pediatria  0.700666  0.024  0.145038  0.246065  0.000000   
10           Psiquiatria  0.028559  0.000  1.000000  1.000000  0.735043   
11         Traumatologia  0.197767  0.056  0.099237  0.448045  0.555556   
12              Urologia 

In [8]:
NI = np.float64(datosNP[:, 1])
MO = np.float64(datosNP[:, 2])
RE = np.float64(datosNP[:, 3])
NE = np.float64(datosNP[:, 4])
ICM = np.float64(datosNP[:, 5])
ES = np.float64(datosNP[:, 6])

In [9]:
X = np.c_[NI,MO,RE,NE,ICM,ES]
print(X)

[[0.35838523 0.304      0.24427481 0.25790088 0.56410256 0.44395787]
 [1.         0.024      0.22137405 0.06526028 0.00854701 0.44799522]
 [0.         0.328      0.50381679 0.35605298 1.         0.08296841]
 [0.04036934 0.176      0.28244275 0.         0.67521368 0.16001965]
 [0.04487868 0.472      0.22900763 0.29437578 0.47008547 0.13015615]
 [0.79063775 1.         0.40458015 0.78111035 0.45299145 1.        ]
 [0.01567533 0.408      0.32061069 0.02004912 0.82051282 0.08548907]
 [0.03457161 0.168      0.16030534 0.79966987 0.30769231 0.04411168]
 [0.10757999 0.         0.         0.78871935 0.26495726 0.        ]
 [0.70066566 0.024      0.14503817 0.24606466 0.         0.23617371]
 [0.02855916 0.         1.         1.         0.73504274 0.12133382]
 [0.1977668  0.056      0.09923664 0.44804541 0.55555556 0.29590071]
 [0.1442989  0.16       0.28244275 0.10491566 0.23931624 0.16796616]]


In [10]:
#Calculo las dos primeras componentes principales
N  = len(X)
xm = np.ones((1,N))
xmedia = (xm@X)/N
Xest = X-xmedia
XeT = np.transpose(Xest)
print(Xest)

[[ 0.09197073  0.064      -0.05519671 -0.13918868  0.09533202  0.19656769]
 [ 0.7335855  -0.216      -0.07809748 -0.33182929 -0.46022354  0.20060503]
 [-0.2664145   0.088       0.20434527 -0.04103658  0.53122945 -0.16442178]
 [-0.22604516 -0.064      -0.01702877 -0.39708956  0.20644313 -0.08737054]
 [-0.22153582  0.232      -0.07046389 -0.10271378  0.00131492 -0.11723404]
 [ 0.52422325  0.76        0.10510863  0.38402079 -0.01577909  0.75260981]
 [-0.25073917  0.168       0.02113917 -0.37704045  0.35174227 -0.16190112]
 [-0.23184288 -0.072      -0.13916618  0.40258031 -0.16107824 -0.20327851]
 [-0.15883451 -0.24       -0.29947152  0.39162979 -0.20381328 -0.24739019]
 [ 0.43425117 -0.216      -0.15443335 -0.15102491 -0.46877055 -0.01121648]
 [-0.23785534 -0.24        0.70052848  0.60291044  0.26627219 -0.12605637]
 [-0.06864769 -0.184      -0.20023488  0.05095585  0.08678501  0.04851052]
 [-0.12211559 -0.08       -0.01702877 -0.29217391 -0.22945431 -0.07942403]]


In [11]:
A = (XeT@Xest)/N
print(A)

[[ 0.10763009  0.01414182 -0.01427536 -0.01302109 -0.06068581  0.06213842]
 [ 0.01414182  0.07150277  0.00652496  0.00524592  0.02205391  0.04477477]
 [-0.01427536  0.00652496  0.05628284  0.02605763  0.03617779  0.0025198 ]
 [-0.01302109  0.00524592  0.02605763  0.10605741  0.00422965  0.00632821]
 [-0.06068581  0.02205391  0.03617779  0.00422965  0.08369265 -0.01312707]
 [ 0.06213842  0.04477477  0.0025198   0.00632821 -0.01312707  0.06516371]]


In [12]:
e = np.linalg.eigh(A)
AVL = np.flip(e[0])
print("Autovalores= ", AVL)
AVC = np.flip(e[1], 1)
print("Autovectores (matriz U)=\n", AVC)
U = AVC

Autovalores=  [0.19544273 0.13403377 0.09911562 0.04479706 0.01249687 0.00444341]
Autovectores (matriz U)=
 [[-0.70987656 -0.09388894  0.05114108 -0.35586285 -0.23297336 -0.55111685]
 [-0.12902947 -0.52392663 -0.43110381  0.47086118  0.46819274 -0.28650846]
 [ 0.21334877 -0.37011933  0.01548632 -0.76376791  0.47676026  0.08131668]
 [ 0.15119256 -0.54404102  0.77438197  0.22002993 -0.14364885 -0.1115553 ]
 [ 0.48419142 -0.31628427 -0.43013031 -0.14038158 -0.63002624 -0.25272672]
 [-0.42024809 -0.4285803  -0.16314027 -0.0137773  -0.28574564  0.72887265]]


In [13]:
Z = Xest@U
print("Matriz Z=\n", Z)

Matriz Z=
 [[-0.14281444 -0.06040967 -0.20460046 -0.00715308 -0.11401373  0.06119552]
 [-0.86685707  0.31331282  0.03769206 -0.31428276 -0.0289715  -0.04921251]
 [ 0.54147388 -0.1719503  -0.28184937 -0.10116837 -0.08111868 -0.11129112]
 [ 0.24172728  0.24924071 -0.36627606 -0.05183668 -0.03347786  0.06997087]
 [ 0.14666936  0.03103765 -0.17341659  0.22072469  0.17406367 -0.02443046]
 [-0.71363325 -1.01279186 -0.11781694  0.16736654  0.02353018  0.01159735]
 [ 0.34217044  0.0909605  -0.50177689  0.02208026  0.02596734 -0.07306698]
 [ 0.21248087  0.03004577  0.43122608  0.26888569  0.0556937  -0.01528074]
 [ 0.14432021  0.20892222  0.52200085  0.29043363 -0.07529696 -0.04054889]
 [-0.55843734  0.36479119  0.19944621 -0.10555735  0.04431109 -0.06285223]
 [ 0.62232912 -0.46940519  0.47506545 -0.46638862  0.05868604  0.03038177]
 [ 0.05909119  0.1009971   0.06692789  0.08908413 -0.24147667  0.08200873]
 [-0.02852025  0.32524906 -0.08662223 -0.01218806  0.19210337  0.12152869]]


In [14]:
z1 = Z[:, 0]
print("Primera componente principal: ", z1)
z2 = Z[:, 1]
print("Segunda componente principal: ", z2)
z3 = Z[:, 2]
z4 = Z[:, 3]
z5 = Z[:, 4]
z6 = Z[:, 5]

Primera componente principal:  [-0.14281444 -0.86685707  0.54147388  0.24172728  0.14666936 -0.71363325
  0.34217044  0.21248087  0.14432021 -0.55843734  0.62232912  0.05909119
 -0.02852025]
Segunda componente principal:  [-0.06040967  0.31331282 -0.1719503   0.24924071  0.03103765 -1.01279186
  0.0909605   0.03004577  0.20892222  0.36479119 -0.46940519  0.1009971
  0.32524906]


In [15]:
# Porcentaje de variabilidad explicada por z1 y z2:
print("Varianza explicada por la CP 1: ", AVL[0]/sum(AVL))
print("Varianza explicada por la CP 2: ", AVL[1]/sum(AVL))
print("Varianza explicada por la CP 3: ", AVL[2]/sum(AVL))
print("Varianza explicada por la CP 4: ", AVL[3]/sum(AVL))
print("Varianza explicada por la CP 5: ", AVL[4]/sum(AVL))

Varianza explicada por la CP 1:  0.39859471690680215
Varianza explicada por la CP 2:  0.27335451524861154
Varianza explicada por la CP 3:  0.2021408526559395
Varianza explicada por la CP 4:  0.09136115097188427
Varianza explicada por la CP 5:  0.025486670234011275


In [16]:
# Es adecuado tomar dos componentes principales?
# No, no es adecuado, una varianza explicada en un 66% deja lugar a mucho error, lo cual puede llevar a una
# mala administración hospitalaria. Se deberían tomar las 3 primeras componentes principales, ya que la tercera (z3) explica una
# parte de la variabilidad muy grande.

In [17]:
# Busco la correlación entre estas nuevas variables y las originales.
x1  = X[:, 0]
x2  = X[:, 1]
x3  = X[:, 2]
x4  = X[:, 3]
x5  = X[:, 4]
x6  = X[:, 5]
xe1 = x1-sum(x1)/len(x1)
xe2 = x2-sum(x2)/len(x2)
xe3 = x3-sum(x3)/len(x3)
xe4 = x4-sum(x4)/len(x4)
xe5 = x5-sum(x5)/len(x5)
xe6 = x6-sum(x6)/len(x6)
def CM(x,y):    # Cuadrados minimos con polyfit
    coef = np.polyfit(x,y,1)
    poli = np.poly1d(coef)
    yRL = np.polyval(poli,x)   
    print(poli)
    # R" para datos de media cero
    R2 = np.linalg.norm(yRL, 2)**2 / np.linalg.norm(y,2)**2
    print(R2)
    return(poli,R2)
[p,R2]=CM(z1,xe1)
[p,R2]=CM(z2,xe2)
[p,R2]=CM(z3,xe3)
[p,R2]=CM(z4,xe4)
[p,R2]=CM(z5,xe5)
[p,R2]=CM(z6,xe6)

 
-0.7099 x + 3.849e-17
0.9150640463918284
 
-0.5239 x - 2.502e-17
0.5145556080666434
 
0.01549 x - 1.925e-17
0.0004223404625884382
 
0.22 x - 3.079e-17
0.020449000264594855
 
-0.63 x
0.05926947203217995
 
0.7289 x + 4.619e-17
0.03622547333072977


In [18]:
[p,R2]=CM(z1,Xest[:,0])
[p,R2]=CM(z2,Xest[:,1])
[p,R2]=CM(z3,Xest[:,2])
[p,R2]=CM(z4,Xest[:,3])
[p,R2]=CM(z5,Xest[:,4])
[p,R2]=CM(z6,Xest[:,5]) #De ambas maneras da lo mismo.

 
-0.7099 x + 3.849e-17
0.9150640463918284
 
-0.5239 x - 2.502e-17
0.5145556080666434
 
0.01549 x - 1.925e-17
0.0004223404625884382
 
0.22 x - 3.079e-17
0.020449000264594855
 
-0.63 x
0.05926947203217995
 
0.7289 x + 4.619e-17
0.03622547333072977


In [19]:
# Se obtienen los mismos resultados sin escalar?
datos = pd.read_csv("hospitales.csv")   # dataFrame
datosNP = datos.to_numpy()
print(datos)
print(datosNP)

                Servicio    NI    MO    RE     NE   ICM     ES
0                Cirugia  2158   3.8   3.4   8567  1.17  21879
1        Tocoginecologia  5146   0.3   3.1   3782  0.52  22068
2            Hematologia   489   4.1   6.8  11005  1.68   4980
3            Cardiologia   677   2.2   3.9   2161  1.30   8587
4              Digestivo   698   5.9   3.2   9473  1.06   7189
5       Medicina.Interna  4171  12.5   5.5  21563  1.04  47909
6             Neumologia   562   5.1   4.4   2659  1.47   5098
7   Otorrinolaringologia   650   2.1   2.3  22024  0.87   3161
8           Oftalmologia   990   0.0   0.2  21752  0.82   1096
9              Pediatria  3752   0.3   2.1   8273  0.51  12152
10           Psiquiatria   622   0.0  13.3  27000  1.37   6776
11         Traumatologia  1410   0.7   1.5  13290  1.16  14948
12              Urologia  1161   2.0   3.9   4767  0.79   8959
[['Cirugia' 2158 3.8 3.4 8567 1.17 21879]
 ['Tocoginecologia' 5146 0.3 3.1 3782 0.52 22068]
 ['Hematologia' 489 4.1 6.

In [20]:
NI = np.float64(datosNP[:, 1])
MO = np.float64(datosNP[:, 2])
RE = np.float64(datosNP[:, 3])
NE = np.float64(datosNP[:, 4])
ICM = np.float64(datosNP[:, 5])
ES = np.float64(datosNP[:, 6])

In [21]:
X = np.c_[NI,MO,RE,NE,ICM,ES]
print(X)

[[2.1580e+03 3.8000e+00 3.4000e+00 8.5670e+03 1.1700e+00 2.1879e+04]
 [5.1460e+03 3.0000e-01 3.1000e+00 3.7820e+03 5.2000e-01 2.2068e+04]
 [4.8900e+02 4.1000e+00 6.8000e+00 1.1005e+04 1.6800e+00 4.9800e+03]
 [6.7700e+02 2.2000e+00 3.9000e+00 2.1610e+03 1.3000e+00 8.5870e+03]
 [6.9800e+02 5.9000e+00 3.2000e+00 9.4730e+03 1.0600e+00 7.1890e+03]
 [4.1710e+03 1.2500e+01 5.5000e+00 2.1563e+04 1.0400e+00 4.7909e+04]
 [5.6200e+02 5.1000e+00 4.4000e+00 2.6590e+03 1.4700e+00 5.0980e+03]
 [6.5000e+02 2.1000e+00 2.3000e+00 2.2024e+04 8.7000e-01 3.1610e+03]
 [9.9000e+02 0.0000e+00 2.0000e-01 2.1752e+04 8.2000e-01 1.0960e+03]
 [3.7520e+03 3.0000e-01 2.1000e+00 8.2730e+03 5.1000e-01 1.2152e+04]
 [6.2200e+02 0.0000e+00 1.3300e+01 2.7000e+04 1.3700e+00 6.7760e+03]
 [1.4100e+03 7.0000e-01 1.5000e+00 1.3290e+04 1.1600e+00 1.4948e+04]
 [1.1610e+03 2.0000e+00 3.9000e+00 4.7670e+03 7.9000e-01 8.9590e+03]]


In [22]:
N  = len(X) #Calculo dos primeras componentes principales
xm = np.ones((1,N))
xmedia = (xm@X)/N
Xest = X-xmedia
XeT = np.transpose(Xest)
print(Xest)

[[ 4.28307692e+02  8.00000000e-01 -7.23076923e-01 -3.45730769e+03
   1.11538462e-01  9.20192308e+03]
 [ 3.41630769e+03 -2.70000000e+00 -1.02307692e+00 -8.24230769e+03
  -5.38461538e-01  9.39092308e+03]
 [-1.24069231e+03  1.10000000e+00  2.67692308e+00 -1.01930769e+03
   6.21538462e-01 -7.69707692e+03]
 [-1.05269231e+03 -8.00000000e-01 -2.23076923e-01 -9.86330769e+03
   2.41538462e-01 -4.09007692e+03]
 [-1.03169231e+03  2.90000000e+00 -9.23076923e-01 -2.55130769e+03
   1.53846154e-03 -5.48807692e+03]
 [ 2.44130769e+03  9.50000000e+00  1.37692308e+00  9.53869231e+03
  -1.84615385e-02  3.52319231e+04]
 [-1.16769231e+03  2.10000000e+00  2.76923077e-01 -9.36530769e+03
   4.11538462e-01 -7.57907692e+03]
 [-1.07969231e+03 -9.00000000e-01 -1.82307692e+00  9.99969231e+03
  -1.88461538e-01 -9.51607692e+03]
 [-7.39692308e+02 -3.00000000e+00 -3.92307692e+00  9.72769231e+03
  -2.38461538e-01 -1.15810769e+04]
 [ 2.02230769e+03 -2.70000000e+00 -2.02307692e+00 -3.75130769e+03
  -5.48461538e-01 -5.2507

In [23]:
A = (XeT@Xest)/N
print(A)

[[ 2.33424360e+06  8.23230769e+02 -8.70892899e+02 -1.50621806e+06
  -3.30658166e+02  1.35466815e+07]
 [ 8.23230769e+02  1.11723077e+01  1.06846154e+00  1.62879231e+03
   3.22538462e-01  2.62005154e+04]
 [-8.70892899e+02  1.06846154e+00  9.65869822e+00  8.47891598e+03
   5.54497041e-01  1.54526746e+03]
 [-1.50621806e+06  1.62879231e+03  8.47891598e+03  6.54348658e+07
   1.22920473e+02  7.35836851e+06]
 [-3.30658166e+02  3.22538462e-01  5.54497041e-01  1.22920473e+02
   1.14566864e-01 -7.18985266e+02]
 [ 1.35466815e+07  2.62005154e+04  1.54526746e+03  7.35836851e+06
  -7.18985266e+02  1.42803462e+08]]


In [24]:
e = np.linalg.eigh(A)
AVL = np.flip(e[0])
print("Autovalores= ", AVL)
AVC = np.flip(e[1], 1)
print("Autovectores (matriz U)=\n", AVC)
U = AVC

Autovalores=  [1.44748533e+08 6.48597481e+07 9.64300468e+05 8.07535863e+00
 3.50750848e+00 2.71099463e-02]
Autovectores (matriz U)=
 [[-9.33624002e-02  4.27267285e-02  9.94713214e-01 -5.74185032e-04
   1.77130003e-03  2.11115246e-04]
 [-1.81021307e-04  1.05052138e-05 -1.72249578e-03  1.08522665e-01
   9.94028991e-01 -1.12337346e-02]
 [-1.53081034e-05 -1.28628611e-04 -7.51991001e-04 -9.93170917e-01
   1.07927009e-01 -4.43024611e-02]
 [-9.02173130e-02 -9.95331764e-01  3.42856119e-02  1.08413045e-04
   4.17835142e-05  1.04647287e-05]
 [ 5.06175371e-06 -3.06346101e-06 -2.64557270e-04 -4.28254340e-02
   1.59643941e-02  9.98954979e-01]
 [-9.91536316e-01  8.65395306e-02 -9.67807688e-02  3.95027748e-05
  -3.53647356e-04 -1.29961248e-05]]


In [25]:
Z = Xest@U
print("Matriz Z=\n", Z)

Matriz Z=
 [[-8.85211986e+03  4.25579855e+03 -5.83062643e+02  5.42936795e-01
  -1.92106849e+00  6.91221568e-02]
 [-8.88679660e+03  9.16248448e+03  2.20679865e+03 -1.73806000e+00
  -4.17053896e-01  5.06925896e-02]
 [ 7.83972427e+03  2.95436841e+02 -5.24155670e+02 -2.26806006e+00
   1.87408900e+00  3.17373885e-01]
 [ 5.04358295e+03  9.41833202e+03 -9.89454217e+02 -5.02049049e-01
  -1.64575589e+00 -1.21451911e-02]
 [ 5.76812046e+03  2.02038130e+03 -5.82575114e+02  1.33041598e+00
   2.78988838e+00 -1.63327382e-01]
 [-3.60222145e+04 -6.34090034e+03 -6.54349074e+02  6.88351049e-01
   1.85475992e+00 -2.88251749e-02]
 [ 8.46886108e+03  8.61580678e+03 -7.49109316e+02 -7.09003310e-01
   2.34458995e+00  1.29224756e-01]
 [ 8.63419334e+03 -1.08226597e+04  1.89837577e+02  3.04915634e+00
   7.76304704e-01 -9.70107526e-02]
 [ 1.06745121e+04 -1.07161063e+04  7.18571880e+02  4.60277445e+00
  -2.17442431e-01  6.54372846e-02]
 [ 6.70258755e+02  3.77476262e+03  1.93382397e+03  1.51126580e-01
   7.00084151e

In [26]:
z1 = Z[:, 0]
print("Primera componente principal: ", z1)
z2 = Z[:, 1]
print("Segunda componente principal: ", z2)
z3 = Z[:, 2]
z4 = Z[:, 3]
z5 = Z[:, 4]
z6 = Z[:, 5]

Primera componente principal:  [ -8852.11986369  -8886.7966019    7839.72427099   5043.58295069
   5768.12045722 -36022.21448363   8468.86107909   8634.19333844
  10674.51213574    670.2587547    4603.48256889  -2336.04236209
   4394.43775554]
Segunda componente principal:  [  4255.79855388   9162.48448271    295.43684112   9418.3320245
   2020.38129617  -6340.90033857   8615.80677585 -10822.65970464
 -10716.10625968   3774.76261611 -15463.78794419  -1076.91823324
   6877.36988998]


In [27]:
print("Varianza explicada por la CP 1: ", AVL[0]/sum(AVL)) #Obtengo varianza explicada
print("Varianza explicada por la CP 2: ", AVL[1]/sum(AVL))
print("Varianza explicada por la CP 3: ", AVL[2]/sum(AVL))
print("Varianza explicada por la CP 4: ", AVL[3]/sum(AVL))
print("Varianza explicada por la CP 5: ", AVL[4]/sum(AVL))

Varianza explicada por la CP 1:  0.6874044276344055
Varianza explicada por la CP 2:  0.308016096632215
Varianza explicada por la CP 3:  0.004579420598108082
Varianza explicada por la CP 4:  3.834952368919282e-08
Varianza explicada por la CP 5:  1.6657003837277734e-08


In [28]:
[p,R2]=CM(z1,Xest[:,0])
[p,R2]=CM(z2,Xest[:,1])
[p,R2]=CM(z3,Xest[:,2])
[p,R2]=CM(z4,Xest[:,3])
[p,R2]=CM(z5,Xest[:,4])
[p,R2]=CM(z6,Xest[:,5]) #De ambas maneras da lo mismo.

 
-0.09336 x + 1.261e-13
0.5405203010264724
 
1.051e-05 x
0.0006406814630149032
 
-0.000752 x - 7.842e-17
0.05645716517531479
 
0.0001084 x + 1.009e-12
1.4505125700551533e-15
 
0.01596 x + 1.232e-16
0.007802694262674947
 
-1.299e-05 x - 1.009e-12
3.202041893505257e-20


In [29]:
# NO SE LLEGA A LOS MISMOS RESULTADOS. POR ESO ES IMPORTANTE ESCALAR LAS VARIABLES.
# Se obtienen resultados distintos, por ejemplo las dos primeras componentes principales halladas con el archivo sin escalar
# representan mucho mas porcentaje de información que las del archivo escalado, ésto es así probablemente porque el no escalado
# tenga unos valores mucho más grandes en ciertas columnas que en otras mientras que en el escalado al haber normalizado todos 
# los datos a media 0 se obtiene una información no tan diferente o dispar.

# Además claramente las expresiones de las componentes principales en función de las columnas de Xestrella son diferentes en 
# ambos casos.